### ISSUE TITLE
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory

### ISSUE THREAD

**Issue by jenschiavone** [rbenv/rbenv#1207] opened 2020-01-14 05:17 UTC
Hi,
I get this error when running `gem install bundler`:
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory

I'm setting up new Mac laptop (Catalina 10.15.2)
I installed rbenv with homebrew.
I installed Ruby 2.7.0 with rbenv
I set global Ruby with `rbenv global 2.7.0`

Output of rbenv-doctor script:
```
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20191225)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

```
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jschiavone/.rbenv/shims
```

```
rbenv version
2.7.0 (set by /Users/jschiavone/.rbenv/version)
```

at the end of my .bash_profile I have:
```
export RBENV_ROOT=/usr/local/var/rbenv
eval "$(rbenv init -)"
```
^^ **UPDATE** - the correct path is actually `/usr/local/bin/rbenv` but I made that change and it did not fix the issue.
```
gem env home
/Library/Ruby/Gems/2.6.0
```

Any thoughts? I've seen lots of similar issues, but in most of those cases the PATH was not correct. I also tried installing Ruby 2.6.5 with rbenv and setting that version globally but I had the same results.

**Comment by mislav** [comment] 2020-01-14 16:05
Hi, sorry to hear you're having trouble. This looks wrong to me:

```sh
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jschiavone/.rbenv/shims
```

1. The `shims` path should be at the start of the list, not at the end. This path is added by `rbenv init -`, which you seem to have successfully configured. Is there anything else reordering your PATH after the `rbenv init` line in your bash_profile?
2. Since you've set RBENV_ROOT explicitly, the auto-configured shims path should be `/usr/local/var/rbenv/shims`, not `/Users/jschiavone/.rbenv/shims`.

**Comment by jenschiavone** [comment] 2020-01-14 16:24
Hi. `rbenv init` is not adding the shims path, not sure why. So I had explicitly added it to `/etc/paths`, at the bottom though. I moved it to the top and removed `RBENV_ROOT` from `.bash_profile` and now it's working. Thank you!

**Comment by mislav** [comment] 2020-01-14 16:35
Glad you solved it! I'm going to assume rbenv works for you now and will close this.

**Closed by mislav** 2020-01-14 16:35 UTC

**Comment by yukitakahashi1** [comment] 2020-02-26 09:51
Hi,
I also tries to run ``gem install bundler`` to make GitHub Pages with Jekyll, but I get the same error. I'm also using Mac laptop (Catalina 10.15.3). My ruby version is 2.6.3.
My Output of rbenv-doctor script looks OK for me:
```
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20200224)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```
``echo $PATH``
```
/Users/yuki/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/yuki/anaconda3/bin:/Users/yuki/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
```
``rbenv version``
```
system (set by /Users/yuki/.rbenv/version)
```
Do you have any idea how to fix the error?

**Comment by mislav** [comment] 2020-02-26 11:20
@yukitakahashi1 You will want to switch away from using the `default` system version. Take a look at the `rbenv versions` output and set the listed Ruby version as `rbenv global <version>`. This Ruby version is now your default version when running `ruby`, `gem`, etc. and now you can retry `gem install` or `bundle install` commands.

**Comment by yukitakahashi1** [comment] 2020-02-26 11:39
@mislav Yes, when I run ``rbenv global 2.6.3`` and then set the ``shims`` path again, the error was resolved. Thank you!

**Comment by tobiasboyd** [comment] 2020-05-11 16:19
So I just got a new machine w/ macOS 10.15.4, and after installing rbenv and trying to install rubies with it I am having the same problem:
```[9:15:35] toby:~ $ rbenv global 2.7.0
[9:17:23] toby:~ $ rbenv version
2.7.0 (set by /Users/toby/.rbenv/version)
[9:17:28] toby:~ $ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]```
I am sure I am missing something obvious, but even though rbenv seems to be set up right, and can definitely install rubies, it can't seem to clobber the system version, so running `gem install` fails since it tries to install in `/Library`...

**Comment by jasonkarns** [comment] 2020-05-11 20:16
@tobiasboyd likely root cause here was that another ruby was inserted into your `PATH` in front of rbenv's shims. Future debugging should ensure that `which ruby` finds rbenv's ruby shim.

(ie, `test $(which ruby) == $(rbenv root)/shims/ruby`)

**Comment by neuroccm** [comment] 2020-07-28 03:16
Thanks folks - reading this and between the lines helped fix my issue installing ruby, for installing Jekyll with Apple's new ZSH shell. Thanks again.

**Comment by universumthing** [comment] 2022-01-29 23:16
Trying to install Jekyll but having the same errors

`gem install jekyll`
returns
`ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.`

Any insights/tips? I know that homebrew and ruby and gems are all installed. I believe there's something wrong with the path that ruby was installed...but I'm quite a novice 😅 so I could be wrong.

**Comment by tobiasboyd** [comment] 2022-01-31 18:53
@universumthing so it looks like you aren't using a ruby installed by `rbenv` (so you can't install gems w/o sudo), what happens if you manually run `eval "$(rbenv init -)"` and then re-run `gem install jekyll`? If that works, you will want to look at your `.bashrc` (or `.zshrc`) and see if you need to make some changes so that runs in every new session.

**Comment by rjuevesano** [comment] 2022-03-24 08:52
> Trying to install Jekyll but having the same errors
> 
> `gem install jekyll` returns `ERROR: While executing gem ... (Gem::FilePermissionError) You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.`
> 
> Any insights/tips? I know that homebrew and ruby and gems are all installed. I believe there's something wrong with the path that ruby was installed...but I'm quite a novice 😅 so I could be wrong.

@universumthing do you already have a solution?

**Comment by tobiasboyd** [comment] 2022-03-24 13:43
@rjuevesano I would guess you have a similar problem, your user account doesn't have permissions to write to the system ruby dirs on your mac. The quick wrong way to fix that is by doing `sudo gem install` instead, and if you aren't doing anything but trying to make Jekyll work that might be ok, if you want to do any ruby dev work you will want to use `rbenv` or `rvm` or `chruby` to install a ruby (probably a newer version than Apple ships too...), which your user account will be able to install gems on w/o sudoing.
