### ISSUE TITLE
Application-specific Ruby versions and deployment with Chef

### ISSUE THREAD

**Issue by justsee** [rbenv/rbenv#363] opened 2013-03-18 11:38 UTC
Chef's application-ruby cookbook can be used to deploy Rails applications.

Assuming there is a Rails application which contains a .ruby-version, and Chef is being run under rbenv, the .ruby-version will be ignored when tasks are executed such as:

``` ruby
execute "rbenv exec bundle install ..." do
  cwd new_resource.release_path
  user new_resource.owner
  environment new_resource.environment
end
```

As Chef is run as root, often from /root, that will fail as RBENV_DIR defaults to pwd if not set and will [exit here](https://github.com/sstephenson/rbenv/blob/master/libexec/rbenv#L44). This seems to be catching a few people out [1](https://github.com/RiotGames/rbenv-cookbook/pull/4) and [2](https://github.com/fnichol/chef-rbenv/issues/13).

Obviously a developer can set this in the script to avoid this error:

``` ruby
execute "rbenv exec bundle install ..." do
  cwd new_resource.release_path
  user new_resource.owner
  environment new_resource.environment.update({
    "RBENV_DIR" => new_resource.release_path
  })
end
```

However rbenv will still ignore the application's .ruby-version, which a developer may find surprising considering the working directory has changed and the RBENV_DIR has been specified to the same location where a .ruby-version file exists. This is obviously because rbenv has already been called and set RBENV_VERSION, so checks related to Ruby versions are skipped. Mislav has [previously flagged](https://github.com/sstephenson/rbenv/issues/121) this sort of thing as one of the rbenv gotchas.

The fix is to reset RBENV_VERSION so the version checks are run:

``` ruby
execute "rbenv exec bundle install ..." do
  cwd new_resource.release_path
  user new_resource.owner
  environment new_resource.environment.update({
    "RBENV_DIR" => new_resource.release_path,
    "RBENV_VERSION" => ""
  })
end
```

This ensures the application-specific version is used by rbenv when running deployment-related ruby commands from Chef.

I'm wondering whether:
- this sort of gotcha needs to be documented
- there could be an rbenv modification to avoid this additional environment variable wrangling
- I've missed a much more straightforward way of handling this Chef use-case

Apologies for only words and no action, but I'm an end-user that only started looking into rbenv internals today.

**Comment by mislav** [comment] 2021-05-05 21:54
Duplicate of https://github.com/rbenv/rbenv/issues/121

**Closed by mislav** 2021-05-05 21:54 UTC
