### ISSUE TITLE
'rbenv' or 'rbenv help' Error

### ISSUE THREAD

**Issue by smartepsh** [rbenv/rbenv#839] opened 2015-12-16 19:31 UTC
OS:Mac 10.11.2
brew update
brew install rbenv

When I type command 'rbenv' or 'rbenv help', It throws error like this:

```
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
rbenv 0.4.0
Usage: rbenv <command> [<args>]

Some useful rbenv commands are:

See `rbenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/sstephenson/rbenv#readme
```

Other command works fine, but this is unacceptable...How to fix it?

**Comment by mislav** [comment] 2015-12-16 23:34
Ouch! Thanks for reporting. I've never seen this before. Could you tell us your bash version and your awk version? Thanks!

**Comment by smartepsh** [comment] 2015-12-17 01:10
@mislav bash 3.2 + awk 20121220 (output by 'awk --version'). All of them are default They are the software that comes with the system (I've never change anything except through 'brew update').

**Comment by mislav** [comment] 2015-12-17 01:56
You seem to have installed newest `awk`, likely from homebrew/dups. However, I can't reproduce your issue even with the same version of awk. I've also tried to install `gawk` from Homebrew and `gnu-sed` (since `awk` and `sed` are primary external commands that rbenv help uses) but everything worked without problem.

Could you possibly run `RBENV_DEBUG=1 rbenv help` and paste the output as a gist?

**Comment by smartepsh** [comment] 2015-12-17 01:59
-----------------------------------------------------------------------------------------

+ '[' -z '' ']'
+ RBENV_ROOT=/Users/smartepsh/.rbenv
+ export RBENV_ROOT
+ '[' -z '' ']'
++ pwd
+ RBENV_DIR=/Users/smartepsh
+ export RBENV_DIR
+ shopt -s nullglob
++ abs_dirname /usr/local/bin/rbenv
+++ pwd
++ local cwd=/Users/smartepsh
++ local path=/usr/local/bin/rbenv
++ '[' -n /usr/local/bin/rbenv ']'
++ cd /usr/local/bin
++ local name=rbenv
+++ resolve_link rbenv
++++ type -p greadlink readlink
++++ head -1
+++ /usr/local/bin/greadlink rbenv
++ path=../Cellar/rbenv/0.4.0/bin/rbenv
++ '[' -n ../Cellar/rbenv/0.4.0/bin/rbenv ']'
++ cd ../Cellar/rbenv/0.4.0/bin
++ local name=rbenv
+++ resolve_link rbenv
++++ type -p greadlink readlink
++++ head -1
+++ /usr/local/bin/greadlink rbenv
++ path=../libexec/rbenv
++ '[' -n ../libexec/rbenv ']'
++ cd ../libexec
++ local name=rbenv
+++ resolve_link rbenv
++++ type -p greadlink readlink
++++ head -1
+++ /usr/local/bin/greadlink rbenv
+++ true
++ path=
++ '[' -n '' ']'
++ pwd
++ cd /Users/smartepsh
+ bin_path=/usr/local/Cellar/rbenv/0.4.0/libexec
+ export PATH=/usr/local/Cellar/rbenv/0.4.0/libexec:/usr/local/opt/coreutils/libexec/gnubin:/Users/smartepsh/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
+ PATH=/usr/local/Cellar/rbenv/0.4.0/libexec:/usr/local/opt/coreutils/libexec/gnubin:/Users/smartepsh/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
+ hook_path=:/Users/smartepsh/.rbenv/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks
+ export RBENV_HOOK_PATH=:/Users/smartepsh/.rbenv/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks
+ RBENV_HOOK_PATH=:/Users/smartepsh/.rbenv/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks
+ shopt -u nullglob
+ command=help
+ case "$command" in
++ command -v rbenv-help
+ command_path=/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-help
+ '[' -z /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-help ']'
+ shift 1
+ exec /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-help
+ unset usage
+ '[' '' = --usage ']'
+ '[' -z '' ']'
+ echo 'Usage: rbenv <command> [<args>]'
Usage: rbenv <command> [<args>]
+ '[' -z '' ']'
+ echo

+ echo 'Some useful rbenv commands are:'
Some useful rbenv commands are:
+ print_summaries commands local global shell install uninstall rehash version versions which whence
+ for command in '"$@"'
+ print_summary commands
+ local command=commands
+ local summary usage help
++ documentation_for commands
+++ command_path commands
+++ local command=commands
+++ command -v rbenv-commands
++ local filename=/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-commands
++ '[' -n /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-commands ']'
++ extract_initial_comment_block
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ collect_documentation
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ for command in '"$@"'
+ print_summary local
+ local command=local
+ local summary usage help
++ documentation_for local
+++ command_path local
+++ local command=local
+++ command -v rbenv-local
++ local filename=/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-local
++ '[' -n /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-local ']'
++ extract_initial_comment_block
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ collect_documentation
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ for command in '"$@"'
+ print_summary global
+ local command=global
+ local summary usage help
++ documentation_for global
+++ command_path global
+++ local command=global
+++ command -v rbenv-global
++ local filename=/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-global
++ '[' -n /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-global ']'
++ extract_initial_comment_block
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ collect_documentation
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ for command in '"$@"'
+ print_summary shell
+ local command=shell
+ local summary usage help
++ documentation_for shell
+++ command_path shell
+++ local command=shell
+++ command -v rbenv-shell
+++ command -v rbenv-sh-shell
++ local filename=/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-sh-shell
++ '[' -n /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-sh-shell ']'
++ extract_initial_comment_block
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ collect_documentation
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ for command in '"$@"'
+ print_summary install
+ local command=install
+ local summary usage help
++ documentation_for install
+++ command_path install
+++ local command=install
+++ command -v rbenv-install
++ local filename=/usr/local/bin/rbenv-install
++ '[' -n /usr/local/bin/rbenv-install ']'
++ extract_initial_comment_block
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
++ collect_documentation
      p
    }
  '
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ for command in '"$@"'
+ print_summary uninstall
+ local command=uninstall
+ local summary usage help
++ documentation_for uninstall
+++ command_path uninstall
+++ local command=uninstall
+++ command -v rbenv-uninstall
++ local filename=/usr/local/bin/rbenv-uninstall
++ '[' -n /usr/local/bin/rbenv-uninstall ']'
++ extract_initial_comment_block
++ collect_documentation
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ for command in '"$@"'
+ print_summary rehash
+ local command=rehash
+ local summary usage help
++ documentation_for rehash
+++ command_path rehash
+++ local command=rehash
+++ command -v rbenv-rehash
++ local filename=/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-rehash
++ '[' -n /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-rehash ']'
++ extract_initial_comment_block
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ collect_documentation
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ for command in '"$@"'
+ print_summary version
+ local command=version
+ local summary usage help
++ documentation_for version
+++ command_path version
+++ local command=version
+++ command -v rbenv-version
++ local filename=/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-version
++ '[' -n /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-version ']'
++ extract_initial_comment_block
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ collect_documentation
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ for command in '"$@"'
+ print_summary versions
+ local command=versions
+ local summary usage help
++ documentation_for versions
+++ command_path versions
+++ local command=versions
+++ command -v rbenv-versions
++ local filename=/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-versions
++ '[' -n /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-versions ']'
++ extract_initial_comment_block
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ collect_documentation
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ for command in '"$@"'
+ print_summary which
+ local command=which
+ local summary usage help
++ documentation_for which
+++ command_path which
+++ local command=which
+++ command -v rbenv-which
++ local filename=/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-which
++ '[' -n /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-which ']'
++ extract_initial_comment_block
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ collect_documentation
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ for command in '"$@"'
+ print_summary whence
+ local command=whence
+ local summary usage help
++ documentation_for whence
+++ command_path whence
+++ local command=whence
+++ command -v rbenv-whence
++ local filename=/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-whence
++ '[' -n /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-whence ']'
++ extract_initial_comment_block
++ sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ collect_documentation
++ awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      gsub(/^\n*/, "", str)
      gsub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
awk: syntax error at source line 2
 context is
	 >>>  <<< 
awk: bailing out at source line 41
+ eval ''
+ '[' -n '' ']'
+ echo

+ echo 'See `rbenv help <command>'\'' for information on a specific command.'
See `rbenv help <command>' for information on a specific command.
+ echo 'For full documentation, see: https://github.com/sstephenson/rbenv#readme'
For full documentation, see: https://github.com/sstephenson/rbenv#readme

---------------------------------------------------------------------------------------

**Comment by smartepsh** [comment] 2015-12-17 08:49
@mislav https://gist.github.com/smartepsh/b05d013ef62df7f28dad

**Comment by mislav** [comment] 2015-12-17 11:46
Thanks for sharing. The debug output doesn't reveal anything that would help me track down this issue, unfortunately. You could try to uninstall the `awk` you got through Homebrew (the `awk` that ships with OS X is v20070501), but other than that I don't know what could be the issue here.

You could try poking around the `rbenv-help` source to see if anything fixes the issue or changes the error message. But until I can reproduce this problem, I can't help from my end.

**Comment by smartepsh** [comment] 2015-12-17 15:29
You're right... Just uninstall the awk and 'rbenv help' works as normal.

I think it is caused by mac system update.  Because rbenv works fine under mac os 10.10 before and error occurred after system update to 10.11.2 YESTODAY！

**Comment by mislav** [comment] 2015-12-17 16:24
Thanks for the update. Closing as not a problem with rbenv then, but with an incompatible awk that users are little likely to have installed on their system anyway.

**Closed by mislav** 2015-12-17 16:24 UTC
Labels: unconfirmed
