### ISSUE TITLE
Version installed into ~/.rbenv/versions not seen by rbenv

### ISSUE THREAD

**Issue by Bearzooka** [rbenv/rbenv#1317] opened 2021-03-18 11:49 UTC
Due to the complications related to installing into an Apple Silicon MacBook, I managed to install **Ruby 3.0.0** (using another tool) into `~/.rbenv/versions/` however, `rbenv` is not seeing it when I run `rbenv versions` or letting me use it if I do something like `rbenv local 3.0.0` or similar.

I have tried running `rbenv rehash` with no success.

**Comment by jasonkarns** [comment] 2021-03-18 13:54
Can you run the rbenv-doctor script (from https://github.com/rbenv/rbenv-installer) and share the output?

```
# with curl
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash

# alternatively, with wget
wget -q https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor -O- | bash
```

My initial guess is that `$RBENV_ROOT` isn't set to ~/.rbenv as is the default.

**Comment by Bearzooka** [comment] 2021-03-18 14:09
Sure:
```
Checking for `rbenv' in PATH: /opt/homebrew/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /opt/homebrew/bin/rbenv-install (ruby-build 20210309)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

**Comment by jasonkarns** [comment] 2021-03-18 15:01
what does `rbenv root` print for you? and `ls $(rbenv root)/versions`, `ls $(rbenv root)/versions/*/bin`

**Comment by Bearzooka** [comment] 2021-03-18 17:03
```
rbenv root
/Users/bearzooka/.rbenv

ls $(rbenv root)/versions
3.0.0

ls $(rbenv root)/versions/*/bin
bundle 
bundler
cgrouper
.
.
.
```

**Comment by mislav** [comment] 2021-05-05 20:26
@Bearzooka Everything looks in order to me. Are you saying that `3.0.0` is definitely not listed in the output of `rbenv versions`? And which error is shown when you try to do `rbenv local 3.0.0`?

**Comment by Bearzooka** [comment] 2021-05-05 20:51
The files are there indeed, but if I run `rbenv local 3.0.0` it won't set it and `rbenv versions` won't list it.

**Comment by Bearzooka** [comment] 2021-05-05 20:53
Sadly, since then I had to wipe the device a couple of times (you know, test device) and now I cannot reproduce the error.

**Comment by mislav** [comment] 2021-05-05 20:54
Thanks for the update. You are free to close this if you cannot reproduce anymore.

**Closed** 2021-05-05 20:54 UTC
