### ISSUE TITLE
rbenv install 2.4.1 fails on High Sierra 10.13.2 with the following error. 

### ISSUE THREAD

**Issue by codfather** [rbenv/rbenv#1055] opened 2017-12-08 17:09 UTC
`CONFIGURE_OPTS="--with-openssl-dir=`brew --prefix openssl`" rbenv install 2.4.1
ruby-build: use openssl from homebrew
Downloading ruby-2.4.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.bz2
Installing ruby-2.4.1...
ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.13.2 using ruby-build 20170914)

Inspect or clean up the working tree at /var/folders/88/c6kzzp1s0ml1n0d85gbt6df00000gn/T/ruby-build.20171208170319.9963
Results logged to /var/folders/88/c6kzzp1s0ml1n0d85gbt6df00000gn/T/ruby-build.20171208170319.9963.log

Last 10 log lines:
checking for long long... yes
checking for off_t... yes
checking char bit... 8
checking size of int... 0
checking size of short... 0
checking size of long... 0
checking size of long long... configure: error: in `/var/folders/88/c6kzzp1s0ml1n0d85gbt6df00000gn/T/ruby-build.20171208170319.9963/ruby-2.4.1':
configure: error: cannot compute sizeof (long long)
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.`

This is not just with this version , but any version I try. It would appear to be a gcc/clang issue, but not obvious how to work around it. All suggestions gratefully received. Happy to test potential solutions to get this working.

**Comment by codfather** [comment] 2017-12-09 08:54
[ruby-build.20171209085326.24028.log](https://github.com/rbenv/rbenv/files/1544502/ruby-build.20171209085326.24028.log)

Attached the log file.

**Comment by mislav** [comment] 2017-12-12 13:38
I cannot reproduce using latest ruby-build version and same version of macOS. There must be something additional installed on your system (such as MacPorts) that aborts the build process.

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I'm going to close this since this is the wrong project to report these issues to. If you have more information, please report to https://github.com/sstephenson/ruby-build/issues

**Closed by mislav** 2017-12-12 13:38 UTC

**Comment by dcsaszar** [comment] 2018-02-05 13:47
See https://github.com/rbenv/ruby-build/issues/1169
