### ISSUE TITLE
eval "$(rbenv init -)" every time I start on Mac OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by ginolon** [rbenv/rbenv#815] opened 2015-10-29 22:02 UTC
Why, after followin your guide in the Readme, on Mac OSX 10.11 El Capitan I have to initialize every time Rbenv with this command?

```
eval "$(rbenv init -)"
```

After reboot my Mac have the standard ruby -v and my $PATH is the standard PATH:

```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by mislav** [comment] 2015-10-30 01:39
If you followed the guide in the Readme, how does your `~/.bash_profile` look like? Does it have any rbenv initialization files in it

**Comment by ginolon** [comment] 2015-10-30 22:10
@mislav, i followed this part of the guide:

Homebrew on Mac OS X

As an alternative to installation via GitHub checkout, you can install rbenv and ruby-build using the Homebrew package manager on Mac OS X:

$ brew update
$ brew install rbenv ruby-build
Afterwards you'll still need to add eval "$(rbenv init -)" to your profile as stated in the caveats. You'll only ever have to do this once.

Why it doesn't work?

**Comment by mislav** [comment] 2015-10-30 22:39
What exactly doesn't work?

Can you paste us the output of:

```
grep rbenv ~/.bash_profile`
```

**Comment by ginolon** [comment] 2015-10-31 20:27
grep: /Users/myusername/.bash_profile: No such file or directory

**Comment by mislav** [comment] 2015-11-02 10:02
So one of the installation steps included running this:

```
echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
```

This will create a `~/.bash_profile` file and add a line to it that initializes rbenv every time you start a new Terminal tab. Let me know if that works.

**Comment by egdevelops** [comment] 2015-12-13 18:58
Hello @mislav 

My output from grep shows my multiple attempts to append:

```
grep rbenv ~/.bash_profile`
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
eval "$(rbenv init -)"
eval "$(rbenv init -)"`
```
But I still have the:
```
#Load rbenv automatically by appending
#the following to your profile:
eval "$(rbenv init -)"
```
every time I open my iTerm.

Can you guide me in anyway?

Thank you

**Comment by egdevelops** [comment] 2015-12-13 19:05
I also appended to: `.zshrc`

**Comment by mislav** [comment] 2015-12-14 11:30
@egdevelops If you're using zsh as your login shell (default shell when you open iTerm), then changing `.bash_profile` has no effect and you can clean it up. Also there's no reason why `.bash_profile` should have so many duplicate lines to set up rbenv.

For zsh, ensure that your `~/.zshrc` has this:

```sh
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

Then restart your shell. You should be able to run rbenv commands such as:

```
$ rbenv version
2.2.3 (set by /Users/mislav/.rbenv/version)
$ rbenv shell
rbenv: no shell-specific version configured
```

**Comment by mislav** [comment] 2015-12-14 11:31
Closing since this thread is about configuration issue on users' side and not a bug with rbenv.

**Closed by mislav** 2015-12-14 11:31 UTC
Labels: unconfirmed

**Comment by zmitton** [comment] 2016-01-29 19:21
now you can just use the command `rbenv init` from the command line and it says:

'# Load rbenv automatically by appending
# the following to ~/.bash_profile:
eval "$(rbenv init -)"

**Comment by barronlroth** [comment] 2016-09-14 16:49
@egg-develops Did you ever find a solution? My terminal has the same output every time it opens:

```
# Load rbenv automatically by appending
# the following to ~/.bash_profile:

eval "$(rbenv init -)"

```

My .bash_profile:
```

rbenv init
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
export PATH="/usr/local/bin:$PATH"
export CLICOLOR=1
export NVM_DIR="/Users/barron/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

eval "$(rbenv init -)"
```

**Comment by mislav** [comment] 2016-09-14 20:01
@barronlroth You have 3 lines in your bash profile that call `rbenv init`, but you only need 1.

You can keep this line, but remove other invocations:

```
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
```

**Comment by barronlroth** [comment] 2016-09-16 01:31
@mislav That's the fix! Thank you brother.

**Comment by paulbhartzog** [comment] 2016-10-10 14:13
Is it still necessary or desirable to have this in .bash_profile?
```sh
eval "$(rbenv init -)"
```

The Homebrew section of the docs at https://github.com/rbenv/rbenv
says:

> Afterwards you'll still need to run `rbenv init` for instructions as stated in the caveats. You'll only ever have to do this once.

1. There are no caveats that I could find.
2. If I only have to do `rbenv init` once then why would I want it in my .bash_profile?

Running `rbenv init` manually gets you this:
```sh
Load rbenv automatically by appending
the following to ~/.bash_profile:
eval "$(rbenv init -)"
```
but it doesn't say _why_ you might want to load rbenv automatically, or what will happen if you do **not** put that in your .bash_profile.

I'd like to remove it if it is not necessary or desirable.
For example, is there a test to see if it is or is not performing a useful function?

much thx

**Comment by mislav** [comment] 2016-10-10 14:32
> 1\. There are no caveats that I could find.

Homebrew prints the "Caveats" section when you install its `rbenv` formula.

> 2\. If I only have to do `rbenv init` once then why would I want it in my .bash_profile?

It means that you only have to run it once _manually_ to receive instructions to configure your `.bash_profile`. [The benefits of having `eval ... rbenv init` line](https://github.com/rbenv/rbenv#how-rbenv-hooks-into-your-shell) in your shell initialization file are outlined in the README. The only hard requirement for rbenv functioning is to prepend `~/.rbenv/shims` to your PATH. If you don't want to use `rbenv init`, and you're fine with missing out on other optional features, you can do this manually by editing PATH in your, again, `.bash_profile`.

**Comment by paulbhartzog** [comment] 2016-10-10 14:43
> 1. There are no caveats that I could find.
> Homebrew prints the "Caveats" section when you install its rbenv formula.

ah, much thx

> 2. If I only have to do rbenv init once then why would I want it in my .bash_profile?
> It means that you only have to run it once manually to receive instructions to configure your .bash_profile. The benefits of having eval ... rbenv init line in your shell initialization file are outlined in the README. The only hard requirement for rbenv functioning is to prepend ~/.rbenv/shims to your PATH. If you don't want to use rbenv init, and you're fine with missing out on other optional features, you can do this manually by editing PATH in your, again, .bash_profile.

Great! Thx for the pointer.  Not having to do `rbenv rehash` manually is worth it alone. :-)

**Comment by muescha** [comment] 2017-02-23 03:03
caveats are removed from forumla with https://github.com/Homebrew/homebrew-core/commit/ea9dd0e0dd9abf2d452e5675ffad5169e617a041

**Comment by rahulsharma20** [comment] 2017-05-22 10:17
I have the same problem.
I installed rbenv with homebrew but when I do rbenv init, I get the same error.
Here's the output of `grep rbenv ~/.bash_profile`:
`eval "$(rbenv init -)"`

and output from `rbenv init -` is:

export PATH="/Users/rahulsharma/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/usr/local/Cellar/rbenv/1.1.0/libexec/../completions/rbenv.bash'
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}

Thanks in advance

**Comment by giacman** [comment] 2017-11-08 16:50
I have the same issue, using zsh. 

If I run `rbenv init` following Github documentation on how to install with Homebrew on macOS I get 
```
# Load rbenv automatically by appending
# the following to ~/.zshrc:

eval "$(rbenv init -)"
```
I've added that line at the end of my ~/.zshrc file but, It keeps repeating the same message if I run `rbenv init`. 

I have also followed your answer above and added the two lines:
```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

but still no luck...

**Comment by brsastre** [comment] 2018-09-22 00:14
> So one of the installation steps included running this:
> 
> ```
> echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
> ```
> This will create a `~/.bash_profile` file and add a line to it that initializes rbenv every time you start a new Terminal tab. Let me know if that works.

This fuck*ng worked for me. Sorry about the bad language, but it is appropriate since I have been struggling with this for a few hours.

**Comment by ehsong** [comment] 2019-07-21 22:41
What should I do if `echo 'eval "$(rbenv init -)"' >> ~/.bash_profile` doesn't work? I keep getting the message

```
# Load rbenv automatically by appending
# the following to ~/.bash_profile:

eval "$(rbenv init -)"
```

I did check the bash profile and the eval like was appended to it.

**Comment by SherryWu178** [comment] 2019-12-22 07:10
I found this video quite useful!
https://www.youtube.com/watch?v=-DJz7yC3iOI
