### ISSUE TITLE
rbenv rehash on El Capitan does not working

### ISSUE THREAD

**Issue by alec-c4** [rbenv/rbenv#781] opened 2015-09-15 10:34 UTC
Hi,
After installation of gems like rails and bundle, that need to share their executables in shims directory and running rbenv rehash - nothing happens, there are no executables in shims directory :(

**Comment by mislav** [comment] 2015-09-17 14:53
Ouch! Are there any executables when you list ``ls `rbenv root`/versions/*/bin``? What's your `rbenv --version`?

**Comment by MatthewMDavis** [comment] 2015-10-03 14:52
Seemingly related: my 'rbenv version' output is currently as expected: 2.2.1. But my 'ruby --version' output is 2.0.0p645, which appears to be El Capitan system ruby.

**Comment by harrigan** [comment] 2015-10-03 16:24
Same here. After installing rbenv and ruby-build through GitHub checkout, `ruby --version` showed El Capitan's system Ruby. However, installing rbenv through Homebrew (`brew install rbenv ruby-build`), worked for me.

**Comment by MatthewMDavis** [comment] 2015-10-03 17:30
For me, the problem was related to PATH variables getting screwed up after Apple moved /etc/zshenv path-setting info to /etc/zprofile.

See https://github.com/thoughtbot/dotfiles/pull/421

After moving /etc/zprofile back to where it was under Yosemite, i.e., /etc/zshenv, everything went back to normal.

**Comment by purcell** [comment] 2015-10-08 21:08
Add `setopt no_global_rcs` to your `.zshenv`.

**Comment by mislav** [comment] 2015-10-08 23:52
@MatthewMDavis I really don't condone any of these suggested zsh fixes. I would leave /etc/zprofile untouched on El Capitan, and instead configure rbenv in ~/.zshrc.

**Comment by MatthewMDavis** [comment] 2015-10-09 00:57
@Mislav, I've seen your spirited advocacy elsewhere on this topic, and you
obviously know more about this than I do. I won't encourage anyone to adopt
such scandalous measures. For my part, I needed to get my rbenv working
again, and I did, and until I see an industry-wide proper fix, I'll stick
with what's working.

**Comment by adammcnamara** [comment] 2015-10-09 01:56
Same problem using using bash.

``~/.bash_profile`` contains:
```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

``rbenv global`` shows:
``2.2.3``

``which ruby`` shows:
``/Users/adammcnamara/.rbenv/shims/ruby``

``which rails`` shows:
``/usr/bin/rails``

The latter is incorrect.

**Comment by mislav** [comment] 2015-10-09 14:04
@MatthewMDavis Sure. I'm glad you solved it, I just wanted to point out to others that sudo moving a system `/etc/zprofile` file is not the approach I would want them to take.

**Comment by metaskills** [comment] 2015-10-10 21:07
Maybe this is something related to the init script? When I run it, I see the following:

```
$ eval "$(rbenv init -)"
rbenv: no such command `sh-'
```

**Comment by mislav** [comment] 2015-10-11 01:28
@metaskills Which `rbenv --version` do you have? Can you paste the output of `rbenv init -`? What is your `$PATH`?

**Comment by metaskills** [comment] 2015-10-11 11:36
Well, before posting I had pulled the latest from master, I am also using ZSH too. 

I did some reading on the thoughtbot link @MatthewMDavis posted and hacked my fix by commenting out the path_helper line in `/etc/zprofile` and then adding that same line right before my ZSH env's line for rbenv like so.

```shell
eval `/usr/libexec/path_helper -s`
eval "$(rbenv init -)"
```

I feel this was the least best temporary hack till I get my bearings around the issue more and learn a better way. Before and after, my output of`rbenv init-` was the same, se below.:

```shell
$ rbenv init -
export PATH="/Users/kencollins/.rbenv/shims:${PATH}"
export RBENV_SHELL=zsh
source '/Users/kencollins/.rbenv/libexec/../completions/rbenv.zsh'
rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "`rbenv "sh-$command" "$@"`";;
  *)
    command rbenv "$command" "$@";;
  esac
}
```

Thanks so much for posting back @mislav, huge fan and thanks for the work!

**Comment by metaskills** [comment] 2015-10-11 11:37
I also want to point out that my issue was not with `rehash` but was with initializing rbenv and getting the path all set. Perhaps we should rename this issue's title?

**Comment by mislav** [comment] 2015-10-11 11:48
> I did some reading on the thoughtbot link @MatthewMDavis posted and hacked my fix by commenting out the path_helper line in /etc/zprofile and then adding that same line right before my ZSH env's line for rbenv like so.

Thoughbot people are also wrong about this https://github.com/thoughtbot/dotfiles/pull/426

It's not that complicated. Please follow these steps and see if it fixes things:

1. Revert your `/etc/zprofile` to system setting (i.e. not rename it, not comment it out)
2. Do your PATH initialization in `~/.zshrc` not `~/.zshenv`. Don't call `path_helper` manually.
3. That's it!

**Comment by metaskills** [comment] 2015-10-11 12:48
Confirmed, that was the best fix! Had to do some cleanup on my side including where I was not adding `$HOME/.rbenv/bin` at the right place. All in all, my kit and rbenv are working like a champ and are stronger for it :) Thanks @mislav

**Comment by MatthewMDavis** [comment] 2015-10-11 14:27
@Mislav, simply moving the rbenv init to .zshrc is working, which is great.
I remember that

a. it didn't work way back when, and
b. the zsh documentation was pretty insistent that .zshenv was the place
for path manipulation (although you've shown contrary zsh scripture in your
discussions with thoughtbot, I see)

I assume that a. is now fixed because path_helper is working in a sane
fashion and was not back then. Do you have any insight into what the zsh
people were warning about with path-setting so late in the init process,
and why it's not actually an issue?

**Comment by metaskills** [comment] 2015-10-11 16:57
> the zsh documentation was pretty insistent that .zshenv was the place for path manipulation...

I remember that too, it was one reason I had all the path stuff as part of the env.

**Comment by mislav** [comment] 2015-10-11 18:35
zsh documentation itself fails to leave strong advice about this and the community is generally undecided. But it all makes sense if you look at the list of configuration files that zsh loads in interactive + login mode (default mode for shells in Terminal on OS X):

1. `/etc/zshenv`
2. `~/.zshenv` - not a good idea to set custom PATH because see next step
3. `/etc/zprofile` - El Capitan calls `path_helper`, reorders existing PATH by putting system in front
4. `~/.zprofile`
5. `/etc/zshrc`
6. `~/.zshrc` - better place to finish up setting USER path
7. `/etc/zlogin`
8. `~/.zlogin`

**Comment by metaskills** [comment] 2015-10-11 22:52
@mislav Do you think moving to zshrc vs zshenv for path stuff will impact Pow? I can't seem to get rbenv to work now with it.

**Comment by mislav** [comment] 2015-10-11 23:14
It might; I don't use Pow so I didn't notice. Pow does a hack where it executes your login shell to look for your environment variables. This is rougly what it does:

```sh
login -qf $LOGNAME "$(dscl . -read /Users/$LOGNAME UserShell | awk '{print $2}')" \
  -i -c 'env' | grep ^PATH
```

Can you execute that and check if rbenv shims directory appears correctly in PATH and that it has precedence over system paths?

**Comment by metaskills** [comment] 2015-10-12 00:17
I'm not sure where I would, in my own terminal window the shims path will of course be higher up. The problem is the context of what Pow is doing. It shows that the System ruby is being used meaning it is never executing thing in my zshrc. Basically just like my terminal before moving things to zshrc vs zshenv. If I comment out `eval `/usr/libexec/path_helper -s`` in `/etc/zprofile`, Pow works again. Hope that was helpful info.

**Comment by mislav** [comment] 2015-10-12 10:51
@metaskills You can run that command in your own terminal window because it will start a new environment within and ignore the calling environment. So it doesn't matter that the PATH in your terminal is already set up.

Also, if you pass `-x` in the command above, you will get verbose output of everything that is executed during login shell startup. You can then inspect that (often very long) output and see exactly what was changed and when. Let us know what you find!

**Comment by metaskills** [comment] 2015-10-12 11:39
Thanks @mislav I did indeed see the shims path way up at the top of my path above system ones. Does that tell you anything? Still can only get Pow working with my hack above.

**Comment by mislav** [comment] 2015-10-12 11:46
Hm, not sure what's wrong in Pow then. Which version do you use?

You can always create a page in your webapp that echoes `ENV["PATH"]` to the browser so that you can inspect the order of paths and see if rbenv shims are there. I'm guessing that `/usr/bin` takes precedence over rbenv shims, but I don't know why.

**Comment by rocknruby** [comment] 2015-10-14 18:47
@mislav :+1:

**Comment by meetajhu** [comment] 2015-11-04 08:29
After installing zsh i too had issue with switching ruby version under 10.11 El capitan 

I added this line into my .zshrc file

eval "$(rbenv init -)"

and restarted terminal was able to switch versions. Thanks @mislav

**Comment by mislav** [comment] 2015-12-23 13:07
@alec-c4 I'm sorry that we hijacked your original report to talk about unrelated issues. Do you still have the original problem of running `rbenv rehash` and no shims get generated in the `` `rbenv root`/shims `` directory? Is it possible that you have two different installations of rbenv somehow? If there is no further info, I'll be closing this issue since there's nothing I can do about this.

**Comment by Prajna** [comment] 2016-01-07 02:41
@mislav Sorry, I'm a newbie here. Would you please tell me how I should modify /etc/zprofile?
It's like this on my machine:

```
# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```

**Comment by mislav** [comment] 2016-01-07 14:47
@Prajna Your `/etc/zprofile` is fine; you don't need to edit it! It was only necessary to rename it from `/etc/zshenv` on older versions of OS X. They fixed it in El Capitan.

I'm closing this issue since this is a user configuration issue and nothing I can do from rbenv.

**Closed by mislav** 2016-01-07 14:47 UTC
Labels: unconfirmed
