### ISSUE TITLE
Failing to compile Ruby 2.3.0 on FreeBSD 11.0-CURRENT

### ISSUE THREAD

**Issue by duncan-bayne** [rbenv/rbenv#881] opened 2016-03-11 03:00 UTC
I'm trying to install Ruby 2.3.0 on FreeBSD 11.0-CURRENT, and it's failing in the following way:

```
Downloading ruby-2.3.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
Installing ruby-2.3.0...

BUILD FAILED (FreeBSD 11.0-CURRENT using ruby-build 20160228-5-g522f3ba)

Inspect or clean up the working tree at /tmp/ruby-build.20160311195747.1001
Results logged to /tmp/ruby-build.20160311195747.1001.log

Last 10 log lines:
/tmp/ruby-build.20160311195747.1001/ruby-2.3.0 /tmp/ruby-build.20160311195747.1001 ~
checking for ruby... false
checking build system type... x86_64-unknown-freebsd11.0
checking host system type... x86_64-unknown-freebsd11.0
checking target system type... x86_64-unknown-freebsd11.0
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/ruby-build.20160311195747.1001/ruby-2.3.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

I've uploaded [config.log](https://github.com/rbenv/rbenv/files/168388/config.log.txt).

Oddly, if I change into `/tmp/ruby-build.20160311195747.1001/ruby-2.3.0` and run `./configure`, it succeeds.

I'm happy to help with any debugging and / or testing if required.

**Comment by kirillrdy** [comment] 2016-03-11 03:13
@duncan-bayne you tmp is mounted with noexec

**Comment by duncan-bayne** [comment] 2016-03-11 03:15
That was uncannily fast @kirillrdy :)  Guess I was right in my guess about permissions.  Is this an issue with my settings then, or should rbenv not be using /tmp for autoconf purposes?  My understanding is that it's building a trivial binary then checking to see whether it's executable.

**Comment by duncan-bayne** [comment] 2016-03-11 03:21
I mean I can trivially change how I'm mounting tmp, but perhaps rbenv should be doing something different here too.

**Comment by kirillrdy** [comment] 2016-03-11 04:26
I would say that error message from configure is enough to figure out that its not rbenv's problem.

**Comment by duncan-bayne** [comment] 2016-03-11 04:32
But if FreeBSD is mounting tmp as noexec by default (it wasn't a deliberate change on my part!), that means rbenv is broken out of the box on that OS, which seems like an rbenv problem.

**Comment by kirillrdy** [comment] 2016-03-12 05:00
Sorry it took a day, I had a closer look.

How did you install FreeBSD? and how did you install rbenv and ruby-build?

I did fresh FreeBSD11-CURRENT-r296485 auto zfs install. I installed rbenv and ruby-build using pkg.
my /tmp didn't have noexec mount option. 
rbenv install 2.3.0 worked ( after I installed readline, zlib, openssl )

Le

**Comment by mislav** [comment] 2016-03-13 22:24
The detection of `/tmp` location being mounted with `noexec` has been added long ago in a4556a7346524a0be578db98edfe788ab454e000 and should fail the build with an informative message. You can try changing TMPDIR environment variable to a location that supports executables.

**Comment by kirillrdy** [comment] 2016-03-14 03:17
@duncan-bayne I can finally reproduce your issue.
something is wrong with gcc compiler. I haven't had a close look, but if you change to base compiler ( clang )
```
env CC=cc rbenv install 2.3.0
```
You will then hit readline issue rbenv/ruby-build#805

**Comment by rterbush** [comment] 2016-05-15 03:39
FWIW, I can confirm that this issue also exists on FreeBSD 10.3. The following produces a successful build.

```shell
$ CC=cc RUBY_CONFIGURE_OPTS=--with-opt-dir=/usr/local rbenv install 2.3.1
```

**Comment by mislav** [comment] 2016-05-18 11:05
@rterbush Thanks for sharing your workaround?

**Comment by jlduran** [comment] 2016-07-17 01:34
@abdulhadad it was fixed in https://github.com/freebsd/freebsd/commit/9816cc566a2d337cec824eb08307958c9d6dc584

**Comment by jlduran** [comment] 2016-08-02 09:47
@mislav This issue is becoming a little confusing, so I decided to post a simple `Vagrantfile` with the  steps required to install Ruby 2.3.1 on FreeBSD 11.

To avoid the problem mentioned by @abdulhadad, version `-BETA3` or higher should be used.

I have contacted the port maintainer with a few suggestions to freshen up both ports: `devel/rbenv` and `devel/ruby-build`, so `gem-rehash` and autocompletion should work. He said that the new revision will come out soon.

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = 'freebsd/FreeBSD-11.0-BETA3'
  config.vm.hostname = 'freebsd'
  config.vm.base_mac = '589CFC000001' # FreeBSD Bug 201904
  config.vm.network 'private_network', ip: '192.168.50.4'
  config.vm.synced_folder '.', '/vagrant', type: 'nfs'
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
    vb.customize ['modifyvm', :id, '--nictype2', 'virtio']
  end

  config.ssh.shell = 'sh'

  config.vm.provision 'shell', inline: <<-ROOT
    pkg upgrade -y
    pkg install -y gdbm rbenv ruby-build

    # Bash configuration
    mount -t fdescfs fdesc /dev/fd
    echo 'fdesc		/dev/fd		fdesc	fs	rw	0	0' >> /etc/fstab

    # Prepare the vagrant user:
    # Change its default shell to Bash
    pw usermod vagrant -s /usr/local/bin/bash
  ROOT

  config.vm.provision 'shell', privileged: false, inline: <<-VAGRANT
    # Initialize rbenv
    echo 'eval "$(rbenv init -)"' > /home/vagrant/.bash_profile

    # Install Ruby 2.3.1 as the vagrant user
    RUBY_CONFIGURE_OPTS="--with-opt-dir=/usr/local" rbenv install 2.3.1
    rbenv global 2.3.1
    # XXX This step will not be necessary in the next rbenv port revision:
    rbenv rehash
  VAGRANT
end
```

**Comment by anicholson** [comment] 2016-08-05 04:47
I agree with @rterbush and @kirillrdy that apart from the `opt-dir` issue, it seems to be compiler-related. I've been able to successully build 2.3.1 and 2.3.0 on 11.0 BETA-3 by using a modern gcc (6, in my case):

`CC=/usr/local/bin/gcc6 RUBY_CONFIGURE_OPTS=—with-opt-dir=/usr/local rbenv install 2.3.1`

**Comment by zsoltf** [comment] 2016-10-05 23:56
Had the same issue on FreeBSD 10.3. Fixed by setting the compiler to clang

```
export CC=clang
rbenv install 2.3.1
```

**Comment by mislav** [comment] 2016-11-25 20:04
Closing the discussion here, since this really belongs to the ruby-build project. Please post future information about FreeBSD there, if there's not already an open issue for a particular failure!

**Closed by mislav** 2016-11-25 20:04 UTC
Labels: unconfirmed
