### ISSUE TITLE
gem update fails on Windows due to ECONNRESET

### ISSUE THREAD

**Issue by pronoym99** [rbenv/rbenv#1574] opened 2024-05-26 17:20 UTC
I have tried out `gem update --system` and it fails with the following error.

```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (Gem::RemoteFetcher::FetchError)
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/remote_fetcher.rb:266:in `rescue in fetch_path'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/remote_fetcher.rb:246:in `fetch_path'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/remote_fetcher.rb:294:in `cache_update_path'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/source.rb:190:in `load_specs'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/spec_fetcher.rb:253:in `tuples_for'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/spec_fetcher.rb:220:in `block in available_specs'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/source_list.rb:94:in `each'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/source_list.rb:94:in `each_source'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/spec_fetcher.rb:215:in `available_specs'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/spec_fetcher.rb:91:in `search_for_dependency'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/commands/update_command.rb:143:in `fetch_remote_gems'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/commands/update_command.rb:168:in `highest_remote_name_tuple'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/commands/update_command.rb:233:in `rubygems_target_version'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/commands/update_command.rb:278:in `update_rubygems'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/commands/update_command.rb:99:in `execute'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/command_manager.rb:255:in `invoke_command'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/command_manager.rb:194:in `process_args'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/command_manager.rb:152:in `run'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
        F:/Ruby33-x64/bin/gem.cmd:20:in `<main>'
```

I ran the command with a disabled firewall and AV software as well but doesn't make any difference. I am not behind any **corporate proxy** and have already added [rubygems.org](https://www.rubygems.org/) to my AV software exclusion list. This is the output which I get on running

 `curl -Lks 'https://git.io/rg-ssl' | ruby`

```
Here's your Ruby and OpenSSL environment:

Ruby:           3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [x64-mingw-ucrt]
RubyGems:       3.5.9
Bundler:        2.5.9
Compiled with:  OpenSSL 3.3.0 9 Apr 2024
Loaded version: OpenSSL 3.3.0 9 Apr 2024
SSL_CERT_FILE:  F:/Ruby33-x64/bin/etc/ssl/cert.pem
SSL_CERT_DIR:   F:/Ruby33-x64/bin/etc/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (An existing connection was forcibly closed by the remote host. - SSL_connect)
RubyGems connection to rubygems.org:      failed  ❌  (Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (https://rubygems.org))
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Even worse, we're not sure why. 😕

Here's the full error information:
Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect
  F:/Ruby33-x64/lib/ruby/3.3.0/net/protocol.rb:46:in `connect_nonblock'
  F:/Ruby33-x64/lib/ruby/3.3.0/net/protocol.rb:46:in `ssl_socket_connect'
  F:/Ruby33-x64/lib/ruby/3.3.0/net/http.rb:1674:in `connect'
  F:/Ruby33-x64/lib/ruby/3.3.0/net/http.rb:1580:in `do_start'
  F:/Ruby33-x64/lib/ruby/3.3.0/net/http.rb:1575:in `start'
  -:108:in `<main>'

You might have more luck using Mislav's SSL doctor.rb script. You can get it here:
https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb
Read more about the script and how to use it in this blog post:
https://mislav.net/2013/07/ruby-openssl/
F:/Ruby33-x64/lib/ruby/3.3.0/net/protocol.rb:46:in `connect_nonblock': An existing connection was forcibly closed by the remote host. - SSL_connect (Errno::ECONNRESET)
        from F:/Ruby33-x64/lib/ruby/3.3.0/net/protocol.rb:46:in `ssl_socket_connect'
        from F:/Ruby33-x64/lib/ruby/3.3.0/net/http.rb:1674:in `connect'
        from F:/Ruby33-x64/lib/ruby/3.3.0/net/http.rb:1580:in `do_start'
        from F:/Ruby33-x64/lib/ruby/3.3.0/net/http.rb:1575:in `start'
```

This is the output which I get on running Mislav's SSL doctor script via

`curl -Lks 'https://raw.githubusercontent.com/mislav/ssl-tools/8b3dec4/doctor.rb' | ruby - rubygems.org`

```
F:/Ruby33-x64/bin/ruby (3.3.1-p55)
OpenSSL 3.3.0 9 Apr 2024: F:/Ruby33-x64/bin/etc/ssl
SSL_CERT_DIR="F:\\Ruby33-x64\\bin\\etc\\ssl\\certs"
SSL_CERT_FILE="F:\\Ruby33-x64\\bin\\etc\\ssl\\cert.pem"

HEAD https://rubygems.org:443
F:/Ruby33-x64/lib/ruby/3.3.0/net/protocol.rb:46:in `connect_nonblock': An existing connection was forcibly closed by the remote host. - SSL_connect (Errno::ECONNRESET)
        from F:/Ruby33-x64/lib/ruby/3.3.0/net/protocol.rb:46:in `ssl_socket_connect'
        from F:/Ruby33-x64/lib/ruby/3.3.0/net/http.rb:1674:in `connect'
        from F:/Ruby33-x64/lib/ruby/3.3.0/net/http.rb:1580:in `do_start'
        from F:/Ruby33-x64/lib/ruby/3.3.0/net/http.rb:1569:in `start'
        from -:61:in `<main>'
```

It should be noted that I have downloaded a brand-new certificate from [GlobalSignRootCA_R3.pem](https://raw.githubusercontent.com/rubygems/rubygems/master/lib/rubygems/ssl_certs/rubygems.org/GlobalSignRootCA_R3.pem), replaced `cert.pem` with it and explicitly stated `SSL_CERT_DIR` and `SSL_CERT_FILE` by editing my Environment variables on my Windows system. 

Finally, my Windows and Ruby config is as follows:

> Edition - Windows 11 Pro
> Version - 21H2
> OS build - 22000.2538
> Processor - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz 3.60 GHz
> System type - 64-bit operating system, x64-based processor
> ruby version - ruby 3.3.1 (2024-04-23 revision c56cd86388) [x64-mingw-ucrt]

I am still unable to rectify the ECONNRESET error I am facing

**Comment by mislav** [comment] 2024-05-29 13:24
Hello, I'm sorry you are having trouble, but I have no ideas on what causes this or how to fix it.

My guess is that the problem is _not_ with certificate validation, because the error message would have been different. Instead, the error seems to be on the network level; specifically that the host is terminating the connection prematurely. I have no idea why Rubygems host would do this. You could try making the connection from different network (e.g. if you were getting an error from work, retry from home network and see if anything changes). Finally, proxies and anti-malware software could also cause this problem, but you seem to have ruled that out.

Do you get errors connecting to other hosts than `rubygems.org`?

**Comment by mislav** [comment] 2024-06-10 08:00
Thanks for checking that. Since `curl` fails too, I would say that this problem is completely unrelated to either Ruby or rbenv, and is instead caused by networking issues. Unfortunately, I don't know what causes it or how to fix it. Closing as a non-rbenv issue; sorry I couldn't be of more help

**Closed by mislav** 2024-06-10 08:00 UTC
