### ISSUE TITLE
Cannot call rspec from VS Code - works from command line, $PATH issue?

### ISSUE THREAD

**Issue by tgmerritt** [rbenv/rbenv#1406] opened 2022-06-09 22:23 UTC
Error when trying to run rspec from VS Code's debugger:
```
Uncaught exception: /Users/tyler/.rbenv/shims/rspec:3: syntax error, unexpected tSTRING_BEG, expecting do or '{' or '('
[ -n "$RBENV_DEBUG" ] && set -x
     ^
/Users/tyler/.rbenv/shims/rspec:3: syntax error, unexpected ']', expecting end-of-input
[ -n "$RBENV_DEBUG" ] && set -x
                    ^

bundler: failed to load command: rdebug-ide (/Users/tyler/.rbenv/versions/2.6.8/bin/rdebug-ide)
/Users/tyler/.rbenv/versions/2.6.8/bin/rdebug-ide:23:in `load': /Users/tyler/.rbenv/shims/rspec:3: syntax error, unexpected tSTRING_BEG, expecting do or '{' or '(' (SyntaxError)
```

VS Code launch.json profile:
```
{
            "name": "Run RSpec - all",
            "type": "Ruby",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "useBundler": true,
            "pathToBundler": "/Users/tyler/.rbenv/shims/bundler",
            "pathToRDebugIDE": "/Users/tyler/.rbenv/shims/rdebug-ide",
            "program": "/Users/tyler/.rbenv/shims/rspec",
            "args": [
              "--pattern",
              "${workspaceRoot}/spec/**/*_spec.rb"
            ],
            "env": {
                "RAILS_ENV": "test"
            }
        },
```

Running `RAILS_ENV=test bundle exec rspec specs/*` from the command line works fine.

rspec shim looks like this:

```
#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

program="${0##*/}"
if [ "$program" = "ruby" ]; then
  for arg; do
    case "$arg" in
    -e* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export RBENV_DIR="${arg%/*}"
        break
      fi
      ;;
    esac
  done
fi

export RBENV_ROOT="/Users/tyler/.rbenv"
exec "/usr/local/bin/rbenv" exec "$program" "$@"
```

Something about VS Code's terminal not having the correct $PATH ?  I'm not sure where to go from here.

**Comment by mislav** [comment] 2022-06-21 11:34
Hi, I'm not sure what the solution is, but I'm guessing the problem is on this line:
```
"program": "/Users/tyler/.rbenv/shims/rspec"
```
It looks like VS Code will attempt to load this as if it were a Ruby program, but rbenv shims are strictly meant to be executed as executables (they are implemented in bash) and they will eventually spawn the real `rspec` Ruby program after resolving the rbenv version.

If something needs an absolute path to a Ruby program, I would avoid hardcoding paths to rbenv shims (or, as a general rule, avoid referencing rbenv anywhere) and just hardcode paths to the real binaries under the Ruby version that you're using.

```
            "pathToBundler": "/Users/tyler/.rbenv/versions/2.6.8/bin/bundler",
            "pathToRDebugIDE": "/Users/tyler/.rbenv/versions/2.6.8/bin/rdebug-ide",
            "program": "/Users/tyler/.rbenv/versions/2.6.8/bin/rspec",
```

A more ideal solution would be to just rely on PATH and avoid ever have to hardcode absolute paths to things. I'm not sure if the launch configuration allows this, but in most contexts, just invoking `bundler` and `rdebug-ide` and `rspec` should work as long as PATH is set up correctly for rbenv.

**Closed by mislav** 2022-06-21 11:34 UTC
