### ISSUE TITLE
Is there any recommended way to obtain the ruby sources (-k) path?

### ISSUE THREAD

**Issue by Nakilon** [rbenv/rbenv#1199] opened 2019-12-03 00:56 UTC
I'm making a Ruby C Extension the first time for my gem. To compile it needs `bignum.c`, `internal.h` and such stuff that is available only if you've installed Ruby with `-k` flag.
I know no universal way to obtain this path to these sources but I can start with rbenv as it's what I use on both my personal computer and personal server. So when I call `rbenv prev` I get `/Users/nakilon/.rbenv/versions/2.3.8` but I want to put the `append_cppflags "-I/Users/nakilon/.rbenv/sources/2.3.8/ruby-2.3.8/"` line to my `extconf.rb`. What is the most reliable way to convert one string into another? Should I use `.sub` and `+` or is there a better way?

**Comment by mislav** [comment] 2019-12-03 03:45
I think `.sub` and `+` is the way to go; I don't see a better approach. There is no build-in way to access this path. As you said, this path is unreliable across different installations, and it will likely only work on your own machines.

Closing since this is a usage question and not a bug with rbenv

**Closed by mislav** 2019-12-03 03:45 UTC

**Comment by Nakilon** [comment] 2019-12-03 04:23
> the current approach you're taking will likely only work on your own machines

I don't customize the `-k` path though -- I guess `ruby-build` generates it and there is a line of code somewhere in it that could be made a method to be potentially reused for external purposes such as building the extension during `gem install`.

**Comment by mislav** [comment] 2019-12-03 10:34
Here's [how to construct that path in shell](https://github.com/rbenv/ruby-build/blob/77e949a3e649f2204c339508a32518dc5730bd53/bin/rbenv-install#L89-L90):

```sh
echo "${RBENV_BUILD_ROOT:-$(rbenv root)/sources}/$(rbenv version-name)"
```

where RBENV_BUILD_ROOT is a path optionally set in the user's environment and defaults to `RBENV_ROOT/sources`.

**Comment by Nakilon** [comment] 2019-12-03 11:42
Thanks, this is interesting, but it points to
```
sources/2.3.8
```
while the path that would work for `-I` is
```
sources/2.3.8/ruby-2.3.8
```
Because of this misterious `ruby-` prefix my approach was
```
append_cppflags "-I#{Dir.glob("#{`rbenvasd root`.chomp}/sources/#{`rbenv version-name`.chomp}/*/").first}"
```
that does not look neat.

**Comment by mislav** [comment] 2019-12-03 19:11
It does not look neat, but it looks correct and it might be the only option you have right now.

More correct approach that respects RBENV_BUILD_ROOT which might be set:

```ruby
build_root = ENV["RBENV_BUILD_ROOT"] || "#{`rbenv root`.chomp}/sources"
include_path = Dir.glob("#{build_root}/#{`rbenv version-name`.chomp}/*").first
append_cppflags "-I#{include_path}"
```

**Comment by Nakilon** [comment] 2020-07-26 14:14
Seems like I can use `ENV["RBENV_ROOT"]` instead of
```
`rbenv root`.chomp
```
and `ENV["RBENV_VERSION"]` instead of
```
`rbenv version-name`.chomp
```

**Comment by jasonkarns** [comment] 2020-07-28 01:35
Note for future visitors:

`RBENV_VERSION` may be set by users in their environment, and the command `rbenv shell` will set that variable (if rbenv is hooked into the shell environment). However, it is not guaranteed to exist. Hence, `rbenv version-name` is the proper and safe way to get that name.

Similarly, `RBENV_ROOT` will be respected by rbenv if set; and _will_ be set within the context of an rbenv plugin. However, it is not guaranteed to be set nor is it required for rbenv to function. `rbenv root` is the proper and safe way to get that path.
