### ISSUE TITLE
Error exec $SHELL on

### ISSUE THREAD

**Issue by rezapci** [rbenv/rbenv#1165] opened 2019-05-19 15:59 UTC
Hello

I can not process SHELL on my windows 10 pro 

bash: /home/rezapci/.bashrc: line 118: syntax error near unexpected token `('
bash: /home/rezapci/.bashrc: line 118: `export PATH=/home/rezapci/ ./benv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1804.2018.817.0_x64__79rhkp1fndgsc:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files/PuTTY:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Users/rezapci/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/rezapci/.anaconda:/mnt/c/Users/rezapci/.conda:/snap/bin >> ~/.bashrc'``

**Comment by jasonkarns** [comment] 2019-05-19 18:09
Can you provide some more details? The issue title seems incomplete and a line number reference to your bashrc isn't all that helpful without also include the contents of that line.

I'm also confused by the export line included here.
```
export PATH=/home/rezapci/./benv/bin:[SNIP]:/snap/bin >> ~/.bashrc'
```

Exporting PATH and redirecting the output to bashrc? I'm assuming some text is missing here. (Also worth noting... your PATH seems to include `benv/bin`, not `rbenv/bin`... Mistake?

**Comment by rezapci** [comment] 2019-05-19 18:22
> Thanks for your response 
I am about to install ROR with rbenv on my windows 10 Linux ubuntu
so I use this 

```
> cd
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec $SHELL

git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
exec $SHELL
```


so I got this syntax error

**Comment by jasonkarns** [comment] 2019-05-19 18:36
What are the actual contents of line 118? I'm assuming it's the first `exec` command that triggers this, which means the ruby-build stuff hasn't even been written to bashrc at that point? Which means the failure is most likely on from the `eval "$(rbenv init -)"` line?

Can you include the contents of your bashrc at the line indicated by the error? And include the output of `rbenv init -`?

Also, side note... If you're only going to use ruby-build via the provided rbenv-install plugin (that is, you won't be invoking `ruby-build` directly), then you don't need to add it to your PATH. Rbenv will automatically discover subcommands (like `install`) from `plugins/*/bin/rbenv-*`.

**Comment by rezapci** [comment] 2019-05-19 22:57
`rezapci@DESKTOP-GCHBDG1:~$ rbenv init -
export PATH="/home/rezapci/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/usr/lib/rbenv/libexec/../completions/rbenv.bash'
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}`

**Comment by rezapci** [comment] 2019-05-19 23:05
rezapci@DESKTOP-GCHBDG1:~$ curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
rbenv already seems installed in `/usr/bin/rbenv'.

`rbenv install' command already available in `/home/rezapci/.rbenv/plugins/ruby-build/bin/rbenv-install'.
Trying to update with git...
From https://github.com/rbenv/ruby-build
 * branch            master     -> FETCH_HEAD
Already up to date.

Running doctor script to verify installation...
Checking for `rbenv' in PATH: /usr/bin/rbenv
Checking for rbenv shims in PATH: not found
  The directory `/home/rezapci/.rbenv/shims' must be present in PATH for rbenv to work.
  Please run `rbenv init' and follow the instructions.

Checking `rbenv install' support: /home/rezapci/.rbenv/plugins/ruby-build/bin/rbenv-install (ruby-build 20190423-2-gd27e745)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK``

**Comment by jasonkarns** [comment] 2019-05-20 00:17
One thing that looks odd to me from the rbenv-init output: your initial issue comments indicate that you're installing rbenv to ~/.rbenv, yet rbenv-init itself is running from '/usr/lib/rbenv/libexec/` ( as indicated by the 3rd line of rbenv init output, which is sourcing the completions script; which is derived from: https://github.com/rbenv/rbenv/blob/4e923221ce57a04ab52bddd638473d566347711f/libexec/rbenv-init#L98

This seems confirmed from the rbenv-doctor output that indicates rbenv is already installed on the system. (presumably `/usr/bin/rbenv` is symlinked to `/usr/lib/rbenv/bin`?)



aside: when dumping command output in markdown, it's useful to use code-fences (3 backticks before and after the code block), or 4-space indent. This will present the text via `<pre>` tags such that markdown won't attempt to render any inline special characters like backticks, underscores, or asterisks. for more info see "Code" under "Examples" on github's [markdown](https://guides.github.com/features/mastering-markdown/) guide. Of course, you can always use `<details>`, `<summary>` and `<pre>` html tags directly. (I edited your comment already so it would render clearly)

I would strongly recommend keeping only a single installation of rbenv on the system. Decide which to remove and we can ensure a functioning installation in that location.

**Comment by mislav** [comment] 2019-05-21 10:02
Thank you @jasonkarns for helping out!

@rezapci Also, check that you don't have RBENV_ROOT configured in your environment, or if you have, that you are conscious of what this setting does.

Closing since all these problems seem to stem from your particular installation woes (I hope you've cleared it up by now!) and because none of this sounds like it's a bug with rbenv.

**Closed by mislav** 2019-05-21 10:02 UTC
