### ISSUE TITLE
Unable to install gems

### ISSUE THREAD

**Issue by dkennell** [rbenv/rbenv#1181] opened 2019-08-29 16:04 UTC
I am trying to set the local version of ruby and install bundler. I have run `rbenv local 2.5.5`. This version is now returned when:
- I run `rbenv local`
- When I look at `rbenv versions` (and it seems to be the successfully selected version)

However, I still get the natively installed version of ruby (2.3.7) when:
- I run `ruby -v`
- I look at `gem env`
- I look at `RUBY_VERSION` in IRB
- When I run `gem install bundler` (I get a `You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.` error)

I use zsh, and have the following block in my `.zshrc`:
```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh)"
```

This is the result of printing out my PATH:
```
/Users/davidkennell/.rbenv/shims
/Users/davidkennell/.rbenv/shims
/Users/davidkennell/.rbenv/bin
/Users/davidkennell/.nvm/versions/node/v10.14.1/bin
/Library/Frameworks/Python.framework/Versions/3.6/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```
... so I don't think path precedence is the problem.

More details:
- `ruby-build` is upgraded to the latest version
- I tried adding `rbenv init` to the `~/.bash_profile`, but that made no difference
- I have `/etc/zshprofile`, not `/etc/zshenv`
- I am on MacOS High Sierra 0.13.6

Any idea what could be causing this? Thanks so much!

**Comment by mislav** [comment] 2019-09-12 07:26
Hmm really weird! Everything seems set up correctly from your end. I can't guess where the problem might be.

1. Do `ruby`/`gem` executables exist in your `~/.rbenv/shims` directory? If not, you may need to run `rbenv rehash`, but I'm not sure how you could have gotten into that state if you do have a `2.5.5` version installed. Do you remember how exactly did you install `2.5.5`?
2. Can you [run rbenv-doctor](https://github.com/rbenv/rbenv-installer#rbenv-doctor) to debug your local setup?

**Comment by sdhull** [comment] 2019-10-25 00:41
I just started getting this problem today as well, maybe started after manually running `rbenv rehash` but I'm not certain. Basically what I've found is `~/.rbenv/shims` is now empty and I have no idea how to repopulate it

```
[2.5.3]  ~ ツ rbenv shell 2.5.3
[2.5.3]  ~ ツ rbenv shell
2.5.3
[2.5.3]  ~ ツ ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
[2.5.3]  ~ ツ ls ~/.zshrc
/Users/stevehull/.zshrc
[2.5.3]  ~ ツ
[2.5.3]  ~ ツ
[2.5.3]  ~ ツ
[2.5.3]  ~ ツ rbenv shell
2.5.3
[2.5.3]  ~ ツ ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
[2.5.3]  ~ ツ ls ~/.rbenv/shims
[2.5.3]  ~ ツ curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20191024)
Counting installed Ruby versions: 5 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
[2.5.3]  ~ ツ ls -alhrt ~/.rbenv/shims
total 0
drwxr-xr-x  5 stevehull  staff   160B Oct 24 17:17 ..
drwxr-xr-x  2 stevehull  staff    64B Oct 24 17:32 .
```

I installed with hombrew, tried upgrading with homebrew, tried reinstalling with homebrew... I'm about to uninstall & install manually using git... wish me luck 😬

**Comment by sdhull** [comment] 2019-10-25 00:44
Actually, I think my ruby installs got corrupted somehow...  maybe I'll try reinstalling rubies first

**Comment by mislav** [comment] 2019-10-25 11:18
Closing this because all these problems look like a bad install/setup and not a bug with rbenv or ruby-build.

If your `shims` directory is empty, but you have Ruby versions installed, try `rbenv rehash` to repopulate it.

**Closed by mislav** 2019-10-25 11:18 UTC
