### ISSUE TITLE
Lots of .rbenv/shims in path...

### ISSUE THREAD

**Issue by iangrant-2nd** [rbenv/rbenv#971] opened 2017-02-21 21:18 UTC
My path looks a bit like this: 

    /Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims:/Users/ian/.rbenv/shims... < A lot more where those came from! >

I uninstalled using Homebrew and reinstalled using Homebrew, to no affect. Got the same result.

The relevant section of my .zshrc:

    echo 'eval "$(rbenv init -)"' >> ~/.zlogin
    export RBENV_ROOT=$HOME/.rbenv

MacOS 0.12.4 Beta (16E163f)

I used to have RVM, but deleted it and went with rbenv last October.

I get  the feeling I'm missing something obvious, but some googling didn't turn up anything. 
Any ideas?

Thanks!

**Comment by pookah-net** [comment] 2017-02-21 21:39
You can close this one... I found the problem!

My .zlogin looked like this:
   eval "$(rbenv init -)"
   eval "$(rbenv init -)"
   eval "$(rbenv init -)"
   eval "$(rbenv init -)"
   eval "$(rbenv init -)"
   eval "$(rbenv init -)"
   eval "$(rbenv init -)"
   ... etc

Not sure why they were there, but deleting all those `eval`'s did the trick!

**Comment by ivanovaleksey** [comment] 2017-04-19 23:02
Hi @pookah-net, seems like the issue is solved and can be closed?

**Comment by pookah-net** [comment] 2017-05-28 16:49
Sorry for the lengthy delay! 

Yep, it can be closed.

**Comment by ivanovaleksey** [comment] 2017-05-28 18:14
@iangrant-2nd since you are creator of the issue you can close it by yourself.

**Closed** 2017-05-29 13:33 UTC

**Comment by pookah-net** [comment] 2017-06-12 00:22
Thanks, @mislav. 

Apologies, @ivanovaleksey, I wasn't thinking!
