### ISSUE TITLE
Issues with Ruby Version Not Matching Gemfile Specification and Bundler Path on macOS Ventura

### ISSUE THREAD

**Issue by mariaLauraDev** [rbenv/rbenv#1559] opened 2024-03-28 03:00 UTC
I am experiencing a mismatch between the Ruby version specified in my Gemfile and the Ruby version detected when running bundle install in my project. Despite setting the Ruby version to 2.3.8 (as confirmed by running ruby -v and rbenv versions), Bundler reports that my Ruby version is 2.6.10, which conflicts with my Gemfile specification.

Additionally, the which bundle command returns /usr/bin/bundle, indicating that Bundler is not using the version managed by rbenv but rather a system-wide version.

**Steps to Reproduce:**

- I checked Ruby version with ruby -v, which outputs ruby 2.3.8p459 (2018-10-18 revision 65136) [-darwin22].
- Run rbenv versions, showing * 2.3.8 (set by /Users/marialaura/.ruby-version).
- Execute which ruby, outputting /Users/marialaura/.rbenv/shims/ruby.
- Execute which bundle, outputting /usr/bin/bundle.
- Run bundle install within my Ruby project directory, encountering the error: Your Ruby version is 2.6.10, but your Gemfile specified 2.3.8.

**Environment:**

macOS Ventura 13.6.5
Shell: zsh
rbenv version: rbenv 1.2.0
Ruby version: 2.3.8, set by rbenv
Bundler version: 
*** LOCAL GEMS ***
Content of .zshrc: 
#openssl
export PATH="/opt/homebrew/opt/openssl@1.0/bin:$PATH"
#openssl arm64
export LDFLAGS="-L/opt/homebrew/opt/openssl@1.0/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.0/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.0/lib/pkgconfig"
#rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh)"
local READLINE_PATH=$(brew --prefix readline)
local OPENSSL_PATH=$(brew --prefix openssl@1.0)
export LDFLAGS="-L$READLINE_PATH/lib -L$OPENSSL_PATH/lib"
export CPPFLAGS="-I$READLINE_PATH/include -I$OPENSSL_PATH/include"
export PKG_CONFIG_PATH="$READLINE_PATH/lib/pkgconfig:$OPENSSL_PATH/lib/pkgconfi$
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$OPENSSL_PATH"
export PATH=$OPENSSL_PATH/bin:$PATH
export SDKROOT="$(xcrun --show-sdk-path)"
export PATH="$HOME/.rbenv/shims:$PATH"
$PATH: /Users/marialaura/.rbenv/shims:/Users/marialaura/.nvm/versions/node/v14.17.0/bin:/opt/homebrew/opt/openssl@1.0/bin:/Users/marialaura/.rbenv/shims:/Users/marialaura/.rbenv/bin:/opt/homebrew/opt/openssl@1.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System ...

**Attempted Solutions:**

- I have confirmed the installation of rbenv and rehashed it.
- I tried to ensure that the PATH is correctly set to prioritize the Ruby version managed by rbenv.
- I installed Bundler for the specified Ruby version and executed rbenv rehash.
- Despite these steps, the issue persists, and I'm seeking guidance on how to ensure that Bundler uses the correct Ruby version as specified by rbenv and my Gemfile.

**Questions:**

- Is there a recommended approach to ensure that the correct Ruby version is used by Bundler in projects managed by rbenv?
- Could there be a configuration issue in my environment that causes Bundler to detect a different Ruby version than the one rbenv manages?
Any help or suggestions would be greatly appreciated as I work to resolve this issue.

**Comment by mislav** [comment] 2024-03-28 12:36
Hi, thank you for the detailed report and I'm sorry this wasn't easier for you. Hopefully it can be fixed quite easily.

The problem is that running `bundle` on your system goes straight to /usr/bin/bundle (your system ruby) rather than the rbenv "bundle" shim. This makes your `bundle install` error out because it always uses the system 2.6 ruby rather than the one you've selected.

To fix this, make sure that your currently selected ruby version has the bundler gem installed:

```
$ gem install bundler
$ rbenv rehash
```
The "rehash" command here might be optional, but it's a good way to ensure that rbenv shims get rebuilt.

After this, running `which bundle` should resolve to the rbenv shim instead of /usr/bin/bundle.

There are other two things I spotted that are not related to your immediate problem but might give you problems in the future:
 
- Your project is using Ruby 2.3. This is a very old Ruby version that will have trouble compiling on recent versions of macOS and requires OpenSSL 1.0. Both Ruby 2.3 and OpenSSL are EOL (End of Life) and thus do not receive any security or build patches. Because of this, going forward it will be increasingly more difficult to install these versions of modern machines, especially newer versions of macOS. My suggestion is to find a way to upgrade the Ruby version in your project, preferably to 3.1 or newer.

- Your PATH environment variable explicitly contains `/opt/homebrew/opt/openssl@1.0/bin`. This should not be necessary, as Ruby 2.3 should compile without this being in your PATH. Having OpenSSL explicitly in your path might negatively affect other projects on your system or other compiled programs that might need a newer OpenSSL. In general, it's best to avoid hardcoding any specific version of a tool. You should try removing that entry from your PATH.

**Comment by mariaLauraDev** [comment] 2024-03-28 13:13
Hi @mislav,

First off, I'd like to extend my deepest thanks for your assistance both through email and on this forum. As I was meticulously going through the issues here, I made sure to consider the advice you've provided in past discussions. Your support has been invaluable!

Following your recommendation, I've removed the hardcoded openssl@1.0 entries from my .zshrc file. Here's the current state of things after making those changes:

> ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [-darwin22]
>  openssl version
OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
>  which bundle
/usr/bin/bundle
> which ruby
/Users/marialaura/.rbenv/shims/ruby
> which gem
/Users/marialaura/.rbenv/shims/gem
>gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: EC lib (https://api.rubygems.org/specs.4.8.gz)
> $PATH
/Users/marialaura/.rbenv/shims:/Users/marialaura/.nvm/versions/node/v14.17.0/bin:/opt/homebrew/opt/openssl@3/bin:/Users/marialaura/.rbenv/shims:/Users/marialaura/.rbenv/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App...\

However, I've hit a snag when attempting to gem install bundler. I encountered an error

**Comment by mariaLauraDev** [comment] 2024-03-29 03:19
Running this doctor script: https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb

> ruby doctor.rb 
/Users/marialaura/.rbenv/versions/2.3.8/bin/ruby (2.3.8-p459)
OpenSSL 1.0.2u  20 Dec 2019: /opt/homebrew/etc/openssl
SSL_CERT_DIR=""
SSL_CERT_FILE=""

HEAD https://status.github.com:443
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: EC lib

**Comment by mislav** [comment] 2024-03-29 03:20
This is a really puzzling error. It hints to your Ruby's inability to make HTTPS requests, most likely due to the OpenSSL 1.0 installation being broken or Ruby's bindings to said OpenSSL being broken.

Do you remember how did you install OpenSSL 1.0 and how did you install Ruby 2.3 on this system?

**Comment by mislav** [comment] 2024-03-29 03:31
Keep in mind that due to what I said above, it's entirely possible that your problem does not have a solution (at least, not one that you or I might find in a reasonable time).

> * Your project is using Ruby 2.3. This is a very old Ruby version that will have trouble compiling on recent versions of macOS and requires OpenSSL 1.0. Both Ruby 2.3 and OpenSSL are EOL (End of Life) and thus do not receive any security or build patches. Because of this, going forward it will be increasingly more difficult to install these versions of modern machines, especially newer versions of macOS.

These kinds of issues are expected to happen with EOL'd software. Regardless of whether you or I find a solution to this, I will close this thread soon, as it is not the goal of rbenv to help you flawlessly manage EOL'd versions of Ruby.

**Comment by monfresh** [comment] 2024-03-29 14:14
@mariaLauraDev If you're still running into issues, I built a paid product called [Ruby on Mac](https://www.rubyonmac.dev/) that is guaranteed to properly install Ruby 2.3.8 and Bundler on your Mac. If this is for your job, you should be able to ask your manager to buy it for you. You'll need the "Ultimate" version for Ruby 2.3. Customers from Brasil get 40% off (I support Purchasing Power Parity).

If you decide to buy it, make sure to carefully read the documentation section called "Installing Ruby versions older than 2.6.10". 

I'm also happy to answer any questions. My email is at the bottom of the Ruby on Mac site.

**Comment by mariaLauraDev** [comment] 2024-04-07 03:29
> Keep in mind that due to what I said above, it's entirely possible that your problem does not have a solution (at least, not one that you or I might find in a reasonable time):
> 
> > * Your project is using Ruby 2.3. This is a very old Ruby version that will have trouble compiling on recent versions of macOS and requires OpenSSL 1.0. Both Ruby 2.3 and OpenSSL are EOL (End of Life) and thus do not receive any security or build patches. Because of this, going forward it will be increasingly more difficult to install these versions of modern machines, especially newer versions of macOS.
> 
> These kinds of issues are expected to happen with EOL'd software. Regardless of whether you or I find a solution to this, I will close this thread soon, as it is not the goal of rbenv to help you flawlessly manage EOL'd versions of Ruby.

I installed folowing this steps:
- using arm64 arch
- I saved this file in the downloads folder: https://raw.githubusercontent.com/rbenv/homebrew-tap/e472b7861b49cc082d1db0f66f265368da107589/Formula/openssl%401.0.rb 
and commented out the "make, test" line in the script. 
- I ran in my terminal brew install ~/Documents/scripts/openssl@1.0.rb
- I added `echo 'export PATH="/opt/homebrew/opt/openssl@1.0/bin:$PATH"' ` to my path
- I installed ruby with flags: `RUBY_CFLAGS="-w -DUSE_FFI_CLOSURE_ALLOC " RUBY_CONFIGURE_OPTS="--with-readline-dir=$(brew --prefix readline) --with-openssl-dir=$(brew --prefix openssl@1.0)" rbenv install 2.3.8`

I really appreciate your technical assessment. After you told me that I could be facing an unsolvable problem, I tried to install it with asdf, and I succeeded! Thank you! I was going to keep trying for weeks to find a solution

**Comment by mariaLauraDev** [comment] 2024-04-07 03:31
I've created a repository to share all my discoveries and learnings, if it's useful to anyone else! I want to share it with the community as a way of saying thank you for all the collaboration I've received.

Repository: https://github.com/mariaLauraDev/install-ruby-2.x-macos-and-tips

**Closed** 2024-04-09 12:20 UTC
